services:
    redis-stack:
      image: redis/redis-stack-server
      ports:
        - "6379:6379"
        - "8001:8001"
      volumes:
        - redis_data:/data
    memcached:
      image: memcached:latest
      container_name: memcached-test
      ports:
        - "11211:11211"
      command: memcached -m 64
volumes:
  redis_data:
  dynamodb-data:
