services:
    redis-stack:
      image: redis/redis-stack-server
      ports:
        - "6379:6379"
        - "8001:8001"
      volumes:
        - redis_data:/data
#    postgres:
#      image: postgres
#      volumes:
#        - postgres_data:/data
#      environment:
#        POSTGRES_PASSWORD: "Postgres2022!"
#      ports:
#        - "5432:5432"
volumes:
  redis_data:
  postgres_data:
